"""empty message

Revision ID: 195d8c62f8f1
Revises: 
Create Date: 2023-09-15 14:46:48.411003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195d8c62f8f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=75), nullable=False),
    sa.Column('hair_style', sa.String(length=75), nullable=False),
    sa.Column('eye_color', sa.String(length=75), nullable=False),
    sa.Column('shirt_color', sa.String(length=75), nullable=False),
    sa.Column('background_color', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('checklist', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('positive_negative', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.Column('reset_counter', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('checklist', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('rewards')
    op.drop_table('habits')
    op.drop_table('dailies')
    op.drop_table('avatars')
    op.drop_table('users')
    # ### end Alembic commands ###
