"""empty message

Revision ID: 73d955804829
Revises: ffdc0a98111c
Create Date: 2023-09-07 11:06:54.418133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d955804829'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=75), nullable=False),
    sa.Column('hair_style', sa.String(length=75), nullable=False),
    sa.Column('eye_color', sa.String(length=75), nullable=False),
    sa.Column('shirt_color', sa.String(length=75), nullable=False),
    sa.Column('background_color', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('checklist', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('repeats', sa.String(length=20), nullable=True),
    sa.Column('repeat_every', sa.Integer(), nullable=True),
    sa.Column('repeat_on', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('positive_or_negative', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.Column('reset_counter', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=450), nullable=True),
    sa.Column('checklist', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('habits')
    op.drop_table('dailies')
    op.drop_table('avatars')
    # ### end Alembic commands ###