"""updated habits table so positive and negative are separate booleans

Revision ID: ad3b701f25b9
Revises: d46d7135d1ef
Create Date: 2023-09-17 11:53:11.512516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3b701f25b9'
down_revision = 'd46d7135d1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative', sa.Boolean(), nullable=True))
        batch_op.drop_column('positive_or_negative')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positive_or_negative', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('negative')
        batch_op.drop_column('positive')

    # ### end Alembic commands ###