"""changes to habits table

Revision ID: d46d7135d1ef
Revises: d58df4313edc
Create Date: 2023-09-16 22:47:02.816150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46d7135d1ef'
down_revision = 'd58df4313edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('positive_or_negative',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('reset_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_counter', sa.VARCHAR(length=15), nullable=True))
        batch_op.alter_column('positive_or_negative',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###